[package]
name = "redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["resp"]

[dependencies]
async-trait = "0.1"
bytes = "1.1"
deadpool = "0.9"
futures = "0.3"
pin-project = "1.0"
resp = { path = "./resp" }
tokio = { version = "1.0", features = ["io-util", "net"] }
tokio-util = { version = "0.7", features = ["io"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt"] }
